name: Build.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build action docker image
#       run: |
#         docker build . -t ameydev/ci-cd-standards-using-opa:latest
